module.exports = {
  compact: true,
  controlFlowFlattening: true,
  controlFlowFlatteningThreshold: 0.2,
  deadCodeInjection: true,
  deadCodeInjectionThreshold: 0.2,
  debugProtection: true,
  debugProtectionInterval: 2000,
  disableConsoleOutput: true,
  identifierNamesGenerator: 'mangled',
  renameGlobals: true,
  seed: true,
  renameProperties: false,
  rotateStringArray: true,
  selfDefending: false,
  // domainLock: ['.ikomida.com', '.ikomida.com.br', '.web.app'],
  shuffleStringArray: true,
  sourceMap: false,
  numbersToExpressions: true,
  simplify: true,
  splitStrings: true,
  splitStringsChunkLength: 3,
  stringArray: true,
  stringArrayEncoding: [
    'rc4',
  ],
  stringArrayThreshold: 0.2,
  target: 'browser-no-eval',
  // transformObjectKeys: true,
  unicodeEscapeSequence: false,
  log: false,
  mangle: true,
}
