name: Deploy to Firebase Hosting on push
on:
  pull_request:
    branches:
      - dev
jobs:
  build_and_deploy_ikomida:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   ssh-key: "${{ secrets.REPO_SSHKEY }}"
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.ARTIFACT_REGISTRY_IKOMIDA_DEV_SERVICE_ACOUNT }}"
      - id: build
        run: |
          gcloud auth activate-service-account artifact-registry@ikomida-dev.iam.gserviceaccount.com --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          npx google-artifactregistry-auth
          rm .npmrc || true
          echo "@ikomida:registry=https://us-central1-npm.pkg.dev/ikomida-dev/node/" >> .npmrc && echo "//us-central1-npm.pkg.dev/ikomida-dev/node/:always-auth=true" >> .npmrc
          yarn install
          yarn dev
          mv ./public/build/bundle.js ./public/build/bundle_old.js
          yarn javascript-obfuscator  ./public/build/bundle_old.js --output  ./public/build/bundle.js --config JsObfuscator.js
          rm ./public/build/bundle_old.js
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_IKOMIDA_DEV }}"
          channelId: live
          projectId: ikomida-dev
